### ISSUE TITLE
Crash on worldGen

### ISSUE THREAD

**Issue by Drakray** [TeamDmfMM/Extra-Food#19]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-23.jar)
  DesertGenLoadingPlugin (Desert-Wells-V0.2 - 1.8.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  ThaumcraftLoader (Thaumcraft-1.8-5.0.3.jar)
  BCModPlugin (zz-backpacks 1.8 - 3.0.4 beta.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1099-universal.jar)
  LoadingPlugin (RandomThings-MC1.8-3.5.6.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 15-11-10 17:44
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.block.state.BlockState cannot be cast to net.minecraft.block.state.IBlockState
	at dmf444.ExtraFood.Common.WorldGen.PeanutWorldGen.generateSurface(PeanutWorldGen.java:64)
	at dmf444.ExtraFood.Common.WorldGen.PeanutWorldGen.generate(PeanutWorldGen.java:26)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:270)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1126)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:180)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:122)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:112)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:126)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4839508056 bytes (4615 MB) / 6018826240 bytes (5740 MB) up to 6018826240 bytes (5740 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms6G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1550 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1550.jar) 
	UCHIJAA	Forge{11.14.3.1550} [Minecraft Forge] (forge-1.8-11.14.3.1550.jar) 
	UCHIJAA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJAA	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHIJAA	backpacks16840{3.0.4} [Backpacks!] (zz-backpacks 1.8 - 3.0.4 beta.jar) 
	UCHIJAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1099-universal.jar) 
	UCHIJAA	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHIJAA	ArmorStatusHUD{1.8} [ArmorStatusHUD] ([1.8]ArmorStatusHUD-client-1.29.jar) 
	UCHIJAA	StatusEffectHUD{1.8} [StatusEffectHUD] ([1.8]StatusEffectHUD-client-1.27.jar) 
	UCHIJAA	antiqueatlas{4.2.7-1.8} [Antique Atlas] (antiqueatlas-4.2.7-1.8.jar) 
	UCHIJAA	chisel{@VERSION@} [Chisel 3] (Chisel_DEV-MC1.8-0.0.1.3.jar) 
	UCHIJAA	CustomSpawner{3.4.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.4.0.jar) 
	UCHIJAA	customnpcs{1.8.0_beta} [CustomNPCs] (CustomNPCs_1.8.0_beta.jar) 
	UCHIJAA	cyclopscore{0.3.0} [Cyclops Core] (CyclopsCore-1.8-0.3.0.jar) 
	UCHIJAA	darkroleplay{0.2.0 } [§4§nDark Roleplay] (Dark Roleplay v0.2.4.jar) 
	UCHIJAA	grim3212core{V0.1 - 1.8} [Grim3212 Core] (Grim3212-Core-V0.1 - 1.8.jar) 
	UCHIJAA	desertwells{V0.1 - 1.8} [Desert Wells] (Desert-Wells-V0.2 - 1.8.jar) 
	UCHIJAA	dragonfruit{V0.1 - 1.8} [Dragon Fruit] (Dragon-Fruit-V0.1 - 1.8.jar) 
	UCHIJAA	MoCreatures{8.0.0.devA} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-8.0.0.devA.jar) 
	UCHIJAA	eplus{3.1.0a1} [Enchanting Plus] (EnchantingPlus-1.8-3.1.0a1.jar) 
	UCHIJAA	evilcraft{0.9.0} [EvilCraft] (EvilCraft-1.8-0.9.0.jar) 
	UCHIJAA	ExtraFood{0.7.0} [Extra Food] (ExtraFood-1.8-0.7.29.jar) 
	UCHIJAA	fireplaces{V0.1 - 1.8} [Fireplaces] (Fireplaces-V0.1 - 1.8.jar) 
	UCHIJAA	gemsplus{1.7.10} [Gems+] (gemsplus-1.6-2-mc1.8.jar) 
	UCHIJAA	LunatriusCore{1.1.2.29} [LunatriusCore] (LunatriusCore-1.8-1.1.2.29-universal.jar) 
	UCHIJAA	InGameInfoXML{2.8.1.78} [InGame Info XML] (InGameInfoXML-1.8-2.8.1.78-universal.jar) 
	UCHIJAA	inventorytweaks{1.60-dev-23-0c708d2} [Inventory Tweaks] (InventoryTweaks-1.60-dev-23.jar) 
	UCHIJAA	IronChest{6.0.107.754} [Iron Chest] (ironchest-1.8-6.0.107.754-universal.jar) 
	UCHIJAA	more{7.0 beta 2} [M-Ore mod] (M-Ore 7 beta 3.jar) 
	UCHIJAA	RadixCore{1.8-2.0.5} [RadixCore] (RadixCore-1.8-2.0.5-universal.jar) 
	UCHIJAA	MCA{1.8-5.0.7.1} [Minecraft Comes Alive] (MCA-1.8-5.0.7.1-universal.jar) 
	UCHIJAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.8-3.0.10B.jar) 
	UCHIJAA	mofood{0.10} [Mo Food] (Mo Food 0.10.jar) 
	UCHIJAA	pokeball{V0.1 - 1.8} [Pokeball] (Pokeball-V0.1 - 1.8.jar) 
	UCHIJAA	RandomThings{3.5.6} [Random Things] (RandomThings-MC1.8-3.5.6.jar) 
	UCHIJAA	corerm{1.2c} [RikMuld's Core] (RikMuldsCore_1.2c.jar) 
	UCHIJAA	globbypotato_rhtiers{1.0} [Rockhounding Ore Tiers] (rockhounding_oretiers_1.8-v1.03.jar) 
	UCHIJAA	Roguelike{1.3.6} [Roguelike Dungeons] (RoguelikeDungeons-1.8-1.3.6.jar) 
	UCHIJAA	Runecraft2{0.1.8} [Runecraft 2] (runecraft2-0.1.8.jar) 
	UCHIJAA	Baubles{1.1.1.0} [Baubles] (Baubles-1.8-1.1.1.0.jar) 
	UCHIJAA	Thaumcraft{5.0.3} [Thaumcraft] (Thaumcraft-1.8-5.0.3.jar) 
	UCHIJAA	Waila{1.6.0_B1} [Waila] (Waila-1.6.0_B1_1.8.1.jar) 
	UCHIJAA	thaumictinkerer{${version}} [Thaumic Tinkerer] (ThaumicTinkerer-3.0-1.8-167.jar) 
	UCHIJAA	thelittlethings{1.1.2} [The Little Things] (The Little Things-v.1.1.2-mc1.8+.jar) 
	UCHIJAA	UsefulFood{1.5.0} [UsefulFood] (UsefulFood-1.8-1.5.0a.jar) 
	UCHIJAA	WailaHarvestability{1.1.5} [Waila Harvestability] (WailaHarvestability-mc1.8-1.1.5.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
FMLPlugin (InventoryTweaks-1.60-dev-23.jar)
  invtweaks.forge.asm.ContainerTransformer
DesertGenLoadingPlugin (Desert-Wells-V0.2 - 1.8.jar)
  grim3212.mc.desertwells.DesertGenClassTransformer
CCCDeobfPlugin (unknown)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
ThaumcraftLoader (Thaumcraft-1.8-5.0.3.jar)
  
BCModPlugin (zz-backpacks 1.8 - 3.0.4 beta.jar)
  brad16840.common.asm.ClassTransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1099-universal.jar)
  org.spongepowered.asm.mixin.transformer.MixinTransformer
LoadingPlugin (RandomThings-MC1.8-3.5.6.jar)
  lumien.randomthings.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Drakray** [comment]
# Configuration file

general {
    # Allow Banana Trees to spawn
    B:GenBananaTrees=true

    # By disabling this, you will not be able to drink water buckets
    B:"Remove&ReplaceWaterBuckets"=true

    # If NEI is installed, it will show mod recipies
    B:UseNEI=true
}


misc {
    # Instead of French Fries, you get Potato Lava
    B:FeelLikeAure=false
}
